### ISSUE TITLE
[Notification] We need to let user who is sharing this link

### ISSUE THREAD

**Issue by upfounders** [zaid4kspr/upfoundersAngular#6]
We need some info like this, we can add sharing person's info above the shared contact or next to it. 
<img width="493" alt="Screen Shot 2020-02-15 at 8 44 24 AM" src="https://user-images.githubusercontent.com/59995322/74591755-73550e00-4fcf-11ea-9e9d-941cd7440d9e.png">

**Comment by zaid4kspr** [comment]
notification will be similar to the one showed in the screenshot in the next update
