### ISSUE TITLE
[Dashboard] Profile image is missing after a while

### ISSUE THREAD

**Issue by upfounders** [zaid4kspr/upfoundersAngular#7]
For the user Nurbiye

<img width="1680" alt="Screen Shot 2020-02-15 at 1 12 31 PM" src="https://user-images.githubusercontent.com/59995322/74595337-f472cc00-4ff4-11ea-99b0-ec97569ee398.png">

**Comment by zaid4kspr** [comment]
this issue is related to heroku hosting it will never happen in a production environement

**Comment by upfounders** [comment]
Got it! that's what I was thinking, thanks for confirming
